import { ArrowLeft, LoaderCircle, XCircle } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../context/useAuth'
import { api } from '../services/api'
import './detail.css'

type Appointment = { id: number; fecha: string; horaInicio: string; horaFin: string; observaciones?: string | null; cliente?: { nombre: string; primerApellido?: string; correo?: string }; empleado?: { nombre: string; primerApellido?: string }; servicio?: { nombre: string; duracionMinutos: number }; estadoCita?: { id?: number; nombre: string } }
type AppointmentStatus = { id: number; nombre: string; activo?: boolean; permiteEdicion?: boolean; permiteCancelacionCliente?: boolean }
function messageFrom(cause: unknown) { return cause instanceof Error ? cause.message : 'Ocurrió un error inesperado.' }
function statusClass(status: string) { return status === 'Confirmada' ? 'status-blue' : status === 'Finalizada' ? 'status-green' : status === 'Cancelada' ? 'status-gray' : 'status-amber' }

export function AppointmentDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const [item, setItem] = useState<Appointment>(); const [statuses, setStatuses] = useState<AppointmentStatus[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [changing, setChanging] = useState(false)
  useEffect(() => { if (!id) return; Promise.all([api.get<Appointment>(`/citas/${id}`), api.list<AppointmentStatus[] | { data: AppointmentStatus[] }>('/estados-cita')]).then(([appointment, statusResult]) => { setItem(appointment); const data = statusResult && typeof statusResult === 'object' && 'data' in statusResult ? statusResult.data : statusResult; setStatuses(data || []) }).catch(cause => setError(messageFrom(cause))).finally(() => setLoading(false)) }, [id])
  async function changeStatus(estadoCitaId: number) { setChanging(true); setError(''); try { await api.patch(`/citas/${id}/estado`, { estadoCitaId }); setMessage('Estado actualizado correctamente.'); navigate(0) } catch (cause) { setError(messageFrom(cause)) } finally { setChanging(false) } }
  async function cancel() { if (!window.confirm('¿Querés cancelar esta cita?')) return; const motivo = window.prompt('Motivo de cancelación:'); if (!motivo || motivo.trim().length < 5) return setError('El motivo debe contener al menos 5 caracteres.'); try { await api.patch(`/citas/${id}/cancelar`, { motivoCancelacion: motivo.trim() }); setMessage('Cita cancelada correctamente.'); navigate(0) } catch (cause) { setError(messageFrom(cause)) } }
  if (loading) return <section className="page-shell"><div className="empty-state"><LoaderCircle className="spin" size={24} /><p>Cargando detalle...</p></div></section>
  if (!item) return <section className="page-shell"><div className="empty-state"><h2>No se encontró la cita</h2><p>{error}</p></div></section>
  const status = item.estadoCita?.nombre || 'Pendiente'; const canManage = user?.rol === 'Administrador' || user?.rol === 'Empleado'
  return <section className="page-shell"><Link className="back-link" to="/citas"><ArrowLeft size={14} /> Volver a citas</Link><div className="section-heading"><div><p className="eyebrow">Detalle de cita #{item.id}</p><h1>{item.servicio?.nombre || 'Cita'}</h1><p className="lead">Información completa y acciones disponibles.</p></div><span className={`status ${statusClass(status)}`}>{status}</span></div>{message && <div className="success-message">{message}</div>}{error && <div className="form-error">{error}</div>}<div className="detail-grid"><article className="panel"><p className="eyebrow">Información</p><h2>Datos de la cita</h2><div className="detail-list"><div><span>Cliente</span><strong>{item.cliente ? `${item.cliente.nombre} ${item.cliente.primerApellido || ''}` : 'Sin cliente'}</strong></div><div><span>Empleado</span><strong>{item.empleado ? `${item.empleado.nombre} ${item.empleado.primerApellido || ''}` : 'Sin empleado'}</strong></div><div><span>Fecha y horario</span><strong>{item.fecha} · {item.horaInicio} - {item.horaFin}</strong></div><div><span>Duración</span><strong>{item.servicio?.duracionMinutos || '--'} minutos</strong></div><div><span>Observaciones</span><strong>{item.observaciones || 'Sin observaciones'}</strong></div></div></article><article className="panel"><p className="eyebrow">Gestión</p><h2>Acciones</h2>{canManage && <><label>Estado<select value={item.estadoCita?.id || ''} onChange={event => changeStatus(Number(event.target.value))} disabled={changing}><option value="">Seleccioná un estado</option>{statuses.map(option => <option key={option.id} value={option.id}>{option.nombre}</option>)}</select></label><Link className="secondary-button" to={`/citas/${id}/editar`}>Editar información</Link></>}{status !== 'Cancelada' && <button className="danger-button" onClick={cancel}><XCircle size={17} /> Cancelar cita</button>}</article></div></section>
}
