import { CalendarDays, LoaderCircle, Plus, Search } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/useAuth'
import { formatShortToday } from '../lib/date'
import { api } from '../services/api'

type Appointment = { id: number; fecha: string; horaInicio: string; cliente?: { nombre: string; primerApellido?: string }; servicio?: { nombre: string }; empleado?: { nombre: string; primerApellido?: string }; estadoCita?: { nombre: string } }
function unwrap<T>(value: T | { data?: T }): T { return (value && typeof value === 'object' && 'data' in value ? value.data : value) as T }
function statusClass(status: string) { return status === 'Confirmada' ? 'status-blue' : status === 'Finalizada' ? 'status-green' : status === 'Cancelada' ? 'status-gray' : 'status-amber' }

export function AppointmentsPage() {
  const { user } = useAuth(); const [items, setItems] = useState<Appointment[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { const endpoint = user?.rol === 'Cliente' && user ? `/citas/cliente/${user.id}` : '/citas'; api.list<Appointment[] | { data: Appointment[] }>(endpoint).then(result => setItems(unwrap(result) || [])).catch(cause => setError(cause instanceof Error ? cause.message : 'No se pudieron cargar las citas.')).finally(() => setLoading(false)) }, [user])
  const filtered = useMemo(() => { const normalized = query.trim().toLowerCase(); return normalized ? items.filter(item => `${item.fecha} ${item.cliente?.nombre || ''} ${item.cliente?.primerApellido || ''} ${item.servicio?.nombre || ''} ${item.empleado?.nombre || ''} ${item.estadoCita?.nombre || ''}`.toLowerCase().includes(normalized)) : items }, [items, query])
  return <section className="page-shell"><div className="section-heading"><div><p className="eyebrow">Operación diaria</p><h1>Citas</h1><p className="lead">Consultá y administrá las citas del establecimiento.</p></div>{user?.rol !== 'Cliente' && <Link className="primary-button" to="/citas/nueva"><Plus size={18} /> Nueva cita</Link>}</div><div className="toolbar"><div className="search-control"><Search size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar cliente o servicio..." /></div><span className="date-button"><CalendarDays size={16} /> {formatShortToday()}</span><span className="results-count">{filtered.length} registros</span></div>{loading && <div className="empty-state"><LoaderCircle className="spin" size={24} /><p>Cargando citas...</p></div>}{error && <div className="empty-state"><h2>No se pudieron cargar las citas</h2><p>{error}</p></div>}{!loading && !error && filtered.length === 0 && <div className="empty-state"><h2>{items.length ? 'No hay coincidencias' : 'No hay citas registradas'}</h2><p>{items.length ? 'Probá con otro término de búsqueda.' : 'Cuando se creen citas desde el sistema aparecerán aquí.'}</p></div>}{!loading && !error && filtered.length > 0 && <div className="table-panel"><table><thead><tr><th>Fecha</th><th>Hora</th><th>Cliente</th><th>Servicio</th><th>Empleado</th><th>Estado</th></tr></thead><tbody>{filtered.map(item => { const status = item.estadoCita?.nombre || 'Pendiente'; return <tr key={item.id}><td><Link className="table-link" to={`/citas/${item.id}`}>{item.fecha}</Link></td><td><Link className="table-link" to={`/citas/${item.id}`}><strong>{item.horaInicio}</strong></Link></td><td>{item.cliente ? `${item.cliente.nombre} ${item.cliente.primerApellido || ''}` : 'Sin cliente'}</td><td>{item.servicio?.nombre || 'Sin servicio'}</td><td>{item.empleado ? `${item.empleado.nombre} ${item.empleado.primerApellido || ''}` : 'Sin empleado'}</td><td><span className={`status ${statusClass(status)}`}>{status}</span></td></tr>})}</tbody></table></div>}<Link className="back-link" to="/">← Volver al resumen</Link></section>
}
