import { Eye, LoaderCircle, Plus, Search } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../services/api'

type Service = { id: number; nombre: string; descripcion?: string; duracionMinutos: number; precioBase: number; activo?: boolean; imagen?: string | null; especialidad?: { nombre: string } }
function unwrap<T>(value: T | { data?: T }): T { return (value && typeof value === 'object' && 'data' in value ? value.data : value) as T }
const apiUrl = import.meta.env.VITE_API_URL || 'http://127.0.0.1:3000'
const sortOptions: { label: string; compare: (a: Service, b: Service) => number }[] = [
  { label: 'Nombre (A-Z)', compare: (a, b) => a.nombre.localeCompare(b.nombre, 'es') },
  { label: 'Nombre (Z-A)', compare: (a, b) => b.nombre.localeCompare(a.nombre, 'es') },
  { label: 'Estado (activos primero)', compare: (a, b) => Number(b.activo !== false) - Number(a.activo !== false) || a.nombre.localeCompare(b.nombre, 'es') },
  { label: 'Estado (inactivos primero)', compare: (a, b) => Number(a.activo !== false) - Number(b.activo !== false) || a.nombre.localeCompare(b.nombre, 'es') },
]

export function ServicesPage() {
  const [services, setServices] = useState<Service[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [sortIndex, setSortIndex] = useState(0)
  useEffect(() => { api.list<Service[] | { data: Service[] }>('/servicios').then(result => setServices(unwrap(result) || [])).catch(cause => setError(cause instanceof Error ? cause.message : 'No se pudo cargar el catálogo.')).finally(() => setLoading(false)) }, [])
  const filtered = useMemo(() => { const normalized = query.trim().toLowerCase(); return normalized ? services.filter(item => `${item.nombre} ${item.descripcion || ''} ${item.especialidad?.nombre || ''}`.toLowerCase().includes(normalized)) : services }, [services, query])
  const sorted = useMemo(() => { const sorter = sortOptions[sortIndex] ?? sortOptions[0]; return [...filtered].sort(sorter.compare) }, [filtered, sortIndex])
  return <section className="page-shell"><div className="section-heading"><div><p className="eyebrow">Catálogo</p><h1>Servicios</h1><p className="lead">Administrá los servicios disponibles para tus citas.</p></div><Link className="primary-button" to="/servicios/nuevo"><Plus size={18} /> Nuevo servicio</Link></div><div className="toolbar"><div className="search-control"><Search size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar servicio..." /></div><label className="sort-control">Ordenar por<select value={sortIndex} onChange={event => setSortIndex(Number(event.target.value))}>{sortOptions.map((option, index) => <option key={option.label} value={index}>{option.label}</option>)}</select></label><span className="results-count">{filtered.length} servicios</span></div>{loading && <div className="empty-state"><LoaderCircle className="spin" size={24} /><p>Cargando servicios...</p></div>}{error && <div className="empty-state"><h2>No se pudo cargar el catálogo</h2><p>{error}</p></div>}{!loading && !error && filtered.length === 0 && <div className="empty-state"><h2>{services.length ? 'No hay coincidencias' : 'No hay servicios registrados'}</h2><p>{services.length ? 'Probá con otro término de búsqueda.' : 'El API no devolvió servicios disponibles.'}</p></div>}{!loading && !error && filtered.length > 0 && <div className="table-panel"><table><thead><tr><th>Servicio</th><th>Duración</th><th>Precio base</th><th>Estado</th><th>Detalle</th></tr></thead><tbody>{sorted.map(service => <tr key={service.id}><td><div className="service-cell">{service.imagen ? <img className="service-thumb service-thumb-image" src={`${apiUrl}/images/download/${service.imagen}`} alt={`Imagen de ${service.nombre}`} /> : <div className="service-thumb">{service.nombre[0]}</div>}<div><strong>{service.nombre}</strong><span>{service.especialidad?.nombre || service.descripcion || 'Sin descripción'}</span></div></div></td><td>{service.duracionMinutos} min</td><td><strong>₡{Number(service.precioBase).toLocaleString('es-CR')}</strong></td><td><span className={`status ${service.activo === false ? 'status-gray' : 'status-green'}`}>{service.activo === false ? 'Inactivo' : 'Activo'}</span></td><td><Link className="icon-button" to={`/servicios/${service.id}`} aria-label={`Ver detalle de ${service.nombre}`}><Eye size={17} /></Link></td></tr>)}</tbody></table></div>}<Link className="back-link" to="/">← Volver al resumen</Link></section>
}
// Lista, busca y ordena los servicios disponibles.
